// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7WziEEH12j_8_Gxfd3HJkypMgy2vLbxQ',
    appId: '1:26707036110:web:17517a8bebfb9274928d9f',
    messagingSenderId: '26707036110',
    projectId: 'portfolio-5a311',
    authDomain: 'portfolio-5a311.firebaseapp.com',
    storageBucket: 'portfolio-5a311.appspot.com',
    measurementId: 'G-GHHQL0LQ53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_lnegNzD0gQQKfsakow7miq-0cT9We18',
    appId: '1:26707036110:android:b1d0777c8198610f928d9f',
    messagingSenderId: '26707036110',
    projectId: 'portfolio-5a311',
    storageBucket: 'portfolio-5a311.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKxaam6F7HZeslJ96s21b3oRgh9OXtR1o',
    appId: '1:26707036110:ios:51d089a94c15911f928d9f',
    messagingSenderId: '26707036110',
    projectId: 'portfolio-5a311',
    storageBucket: 'portfolio-5a311.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKxaam6F7HZeslJ96s21b3oRgh9OXtR1o',
    appId: '1:26707036110:ios:51d089a94c15911f928d9f',
    messagingSenderId: '26707036110',
    projectId: 'portfolio-5a311',
    storageBucket: 'portfolio-5a311.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7WziEEH12j_8_Gxfd3HJkypMgy2vLbxQ',
    appId: '1:26707036110:web:2b5f38feb82faeae928d9f',
    messagingSenderId: '26707036110',
    projectId: 'portfolio-5a311',
    authDomain: 'portfolio-5a311.firebaseapp.com',
    storageBucket: 'portfolio-5a311.appspot.com',
    measurementId: 'G-F238TJY5HW',
  );
}
